version: "1"

#<-- change the order of nodes after finding out what each does and how they interact-->
nodes:
  - id: apply-transforms
    name: Apply AST Transformations for nuxt upgrade
    type: automatic
    steps:
      - name: "Apply absolute watch path transformations"
        js-ast-grep:
          js_file: scripts/absolute-watch-path.ts
          language: "typescript"
          exclude:
            - "**/*.cjs"
            - "**/*.md"
            - "**/*.txt"
      - name: "Apply default data error value transformations"
        js-ast-grep:
          js_file: scripts/default-data-error-value.ts
          language: "typescript"
          exclude:
            - "**/*.cjs"
            - "**/*.md"
            - "**/*.txt"
      - name: "Apply deprecated dedupe value transformations"
        js-ast-grep:
          js_file: scripts/deprecated-dedupe-value.ts
          language: "typescript"
          exclude:
            - "**/*.cjs"
            - "**/*.md"
            - "**/*.txt"
      - name: "Apply template compilation changes transformations"
        js-ast-grep:
          js_file: scripts/template-compilation-changes.ts
          language: "typescript"
          exclude:
            - "**/*.cjs"
            - "**/*.md"
            - "**/*.txt"
      - name: "Apply shallow function reactivity transformations"
        js-ast-grep:
          js_file: scripts/shallow-function-reactivity.ts
          language: "typescript"
          exclude:
            - "**/*.cjs"
            - "**/*.md"
            - "**/*.txt"
